version: '1.0'
services:
  nodejs:
    build: 
      context: .
      dockerfile: Dockerfile
    image: ecaterinaciobanu49/lab4tidpp
    depends_on:
      - mongo
    networks:
      - frontend
      - backend
    environment:
     - MONGO_INITDB_ROOT_USERNAME: root
     - MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - .:/public
    ports:
      - "49161:3000"
    container_name: ecaterina_tidpp0
    
    mongo:
    image: mongo
    restart: always
    environment:
     - MONGO_INITDB_ROOT_USERNAME: root
     - MONGO_INITDB_ROOT_PASSWORD: example
     container_name : ecaterina_tidpp1
     
    mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
     - ME_CONFIG_MONGODB_ADMINUSERNAME: root
     - ME_CONFIG_MONGODB_ADMINPASSWORD: example
     - ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
     container_name : ecaterina_tidpp2
     
    networks:
     frontend:
     backend:
     
